public class BoxColorArray {
    public static void main(String[] args) {
        
        String color1 = "Red";
        String color2 = "Blue";
        String color3 = "Green";
        String color4 = "Yellow";
        String color5 = "Orange";
        String color6 = "Purple";
        String color7 = "Pink";
        String color8 = "Brown";
        String color9 = "Black";
        String color10 = "White";
        String color11 = "Gray";
        String color12 = "Cyan";
        String color13 = "Magenta";
        String color14 = "Teal";
        String color15 = "Maroon";
        String color16 = "Navy";
        String color17 = "Lime";
        String color18 = "Olive";
        String color19 = "Gold";
        String color20 = "Silver";
        String color21 = "Beige";
        String color22 = "Coral";
        String color23 = "Turquoise";
        String color24 = "Indigo";
        String color25 = "Lavender";
        String color26 = "Violet";
        String color27 = "Crimson";
        String color28 = "Peach";
        String color29 = "Azure";
        String color30 = "Mint";

        String[] boxColors = {color1, color2, color3, color4, color5, color6, color7, color8, color9, color10,
                              color11, color12, color13, color14, color15, color16, color17, color18, color19, color20,
                              color21, color22, color23, color24, color25, color26, color27, color28, color29, color30};

        System.out.println("Original Box Colors:");
        System.out.println("Color @ index 0: " + boxColors[0]);
        System.out.println("Color @ index 1: " + boxColors[1]);
        System.out.println("Color @ index 2: " + boxColors[2]);
        System.out.println("Color @ index 3: " + boxColors[3]);
        System.out.println("Color @ index 4: " + boxColors[4]);
        System.out.println("Color @ index 5: " + boxColors[5]);
        System.out.println("Color @ index 6: " + boxColors[6]);
        System.out.println("Color @ index 7: " + boxColors[7]);
        System.out.println("Color @ index 8: " + boxColors[8]);
        System.out.println("Color @ index 9: " + boxColors[9]);
        System.out.println("Color @ index 10: " + boxColors[10]);
        System.out.println("Color @ index 11: " + boxColors[11]);
        System.out.println("Color @ index 12: " + boxColors[12]);
        System.out.println("Color @ index 13: " + boxColors[13]);
        System.out.println("Color @ index 14: " + boxColors[14]);
        System.out.println("Color @ index 15: " + boxColors[15]);
        System.out.println("Color @ index 16: " + boxColors[16]);
        System.out.println("Color @ index 17: " + boxColors[17]);
        System.out.println("Color @ index 18: " + boxColors[18]);
        System.out.println("Color @ index 19: " + boxColors[19]);
        System.out.println("Color @ index 20: " + boxColors[20]);
        System.out.println("Color @ index 21: " + boxColors[21]);
        System.out.println("Color @ index 22: " + boxColors[22]);
        System.out.println("Color @ index 23: " + boxColors[23]);
        System.out.println("Color @ index 24: " + boxColors[24]);
        System.out.println("Color @ index 25: " + boxColors[25]);
        System.out.println("Color @ index 26: " + boxColors[26]);
        System.out.println("Color @ index 27: " + boxColors[27]);
        System.out.println("Color @ index 28: " + boxColors[28]);
        System.out.println("Color @ index 29: " + boxColors[29]);

        boxColors[0] = "UpdatedRed";
        boxColors[1] = "UpdatedBlue";
        boxColors[2] = "UpdatedGreen";
        boxColors[3] = "UpdatedYellow";
        boxColors[4] = "UpdatedOrange";
        boxColors[5] = "UpdatedPurple";
        boxColors[6] = "UpdatedPink";
        boxColors[7] = "UpdatedBrown";
        boxColors[8] = "UpdatedBlack";
        boxColors[9] = "UpdatedWhite";
        boxColors[10] = "UpdatedGray";
        boxColors[11] = "UpdatedCyan";
        boxColors[12] = "UpdatedMagenta";
        boxColors[13] = "UpdatedTeal";
        boxColors[14] = "UpdatedMaroon";
        boxColors[15] = "UpdatedNavy";
        boxColors[16] = "UpdatedLime";
        boxColors[17] = "UpdatedOlive";
        boxColors[18] = "UpdatedGold";
        boxColors[19] = "UpdatedSilver";
        boxColors[20] = "UpdatedBeige";
        boxColors[21] = "UpdatedCoral";
        boxColors[22] = "UpdatedTurquoise";
        boxColors[23] = "UpdatedIndigo";
        boxColors[24] = "UpdatedLavender";
        boxColors[25] = "UpdatedViolet";
        boxColors[26] = "UpdatedCrimson";
        boxColors[27] = "UpdatedPeach";
        boxColors[28] = "UpdatedAzure";
        boxColors[29] = "UpdatedMint";

        System.out.println("Updated Box Colors:");
        System.out.println("Color @ index 0: " + boxColors[0]);
        System.out.println("Color @ index 1: " + boxColors[1]);
        System.out.println("Color @ index 2: " + boxColors[2]);
        System.out.println("Color @ index 3: " + boxColors[3]);
        System.out.println("Color @ index 4: " + boxColors[4]);
        System.out.println("Color @ index 5: " + boxColors[5]);
        System.out.println("Color @ index 6: " + boxColors[6]);
        System.out.println("Color @ index 7: " + boxColors[7]);
        System.out.println("Color @ index 8: " + boxColors[8]);
        System.out.println("Color @ index 9: " + boxColors[9]);
        System.out.println("Color @ index 10: " + boxColors[10]);
        System.out.println("Color @ index 11: " + boxColors[11]);
        System.out.println("Color @ index 12: " + boxColors[12]);
        System.out.println("Color @ index 13: " + boxColors[13]);
        System.out.println("Color @ index 14: " + boxColors[14]);
        System.out.println("Color @ index 15: " + boxColors[15]);
        System.out.println("Color @ index 16: " + boxColors[16]);
        System.out.println("Color @ index 17: " + boxColors[17]);
        System.out.println("Color @ index 18: " + boxColors[18]);
        System.out.println("Color @ index 19: " + boxColors[19]);
        System.out.println("Color @ index 20: " + boxColors[20]);
        System.out.println("Color @ index 21: " + boxColors[21]);
        System.out.println("Color @ index 22: " + boxColors[22]);
        System.out.println("Color @ index 23: " + boxColors[23]);
        System.out.println("Color @ index 24: " + boxColors[24]);
        System.out.println("Color @ index 25: " + boxColors[25]);
        System.out.println("Color @ index 26: " + boxColors[26]);
        System.out.println("Color @ index 27: " + boxColors[27]);
        System.out.println("Color @ index 28: " + boxColors[28]);
        System.out.println("Color @ index 29: " + boxColors[29]);
    }
}
