class ProductFinderRunner {
    public static void main(String... args) {
        String name;

        name = "watch";
        ProductFinder.searchProductAvailability(name);
        name = "pen";
        ProductFinder.searchProductAvailability(name);
        name = "fan";
        ProductFinder.searchProductAvailability(name);
        name = "shirt";
        ProductFinder.searchProductAvailability(name);
        name = "laptop";
        ProductFinder.searchProductAvailability(name);
        name = "mobile";
        ProductFinder.searchProductAvailability(name);
        name = "headphones";
        ProductFinder.searchProductAvailability(name);
        name = "slipper";
        ProductFinder.searchProductAvailability(name);
        name = "shoes";
        ProductFinder.searchProductAvailability(name);
        name = "goldChain";
        ProductFinder.searchProductAvailability(name);
        name = "bags";
        ProductFinder.searchProductAvailability(name);
        name = "belt";
        ProductFinder.searchProductAvailability(name);
        name = "perfume";
        ProductFinder.searchProductAvailability(name);
        name = "chips";
        ProductFinder.searchProductAvailability(name);
        name = "cookies";
        ProductFinder.searchProductAvailability(name);
        name = "mixer";
        ProductFinder.searchProductAvailability(name);
        name = "fridge";
        ProductFinder.searchProductAvailability(name);
        name = "washingMachine";
        ProductFinder.searchProductAvailability(name);
        name = "paint";
        ProductFinder.searchProductAvailability(name);
        name = "cement";
        ProductFinder.searchProductAvailability(name);
        name = "powder";
        ProductFinder.searchProductAvailability(name);
        name = "pickle";
        ProductFinder.searchProductAvailability(name);
        name = "petrol";
        ProductFinder.searchProductAvailability(name);
        name = "motorcycle";
        ProductFinder.searchProductAvailability(name);
        name = "helmet";
        ProductFinder.searchProductAvailability(name);
        name = "sofa";
        ProductFinder.searchProductAvailability(name);
        name = "table";
        ProductFinder.searchProductAvailability(name);
    }
}
